# remediation_service.py
import logging
from datetime import datetime
from typing import List, Optional

from sqlalchemy.orm import Session

from app.models.database import Analysis, ComplianceGap, AuditLog
from app.services.github_service import github_service
from app.config import settings

logger = logging.getLogger("app.services.remediation_service")


def approve_remediation_record(db: Session, analysis: Analysis, note: Optional[str], approver: str) -> Analysis:
    """Marks remediation output as approved and writes the audit trail entry.

    Used both by the human approval API endpoint and by the auto-PR autonomy
    path (approver="AutopilotAgent") so the audit log always shows who/what
    approved a given remediation package.
    """
    analysis.remediation_approval_status = "approved"
    analysis.remediation_approved_at = datetime.utcnow()
    analysis.remediation_approval_note = note
    db.add(AuditLog(
        analysis_id=analysis.id,
        agent_name=approver,
        action="remediation_approved",
        details=note or f"Remediation package approved by {approver}.",
        timestamp=datetime.utcnow(),
    ))
    db.commit()
    db.refresh(analysis)
    return analysis


def build_remediation_markdown(analysis: Analysis, gaps: List[ComplianceGap]) -> str:
    """Assembles the remediation document committed to the fix branch."""
    lines = [
        "# Compliance Autopilot — Remediation Package",
        "",
        f"- **Project:** {analysis.project.name}",
        f"- **Regulation:** {analysis.regulation.name} ({analysis.regulation.source})",
        f"- **Scan:** #{analysis.id}, score {analysis.overall_score:.1f}%",
        f"- **Approved by:** {analysis.remediation_approval_note or 'Human reviewer'}",
        "",
        "This document was generated by the Compliance Autopilot agent pipeline and",
        "approved before this branch was pushed. Each section below is an actionable",
        "remediation plan for a detected compliance gap.",
        "",
    ]
    for gap in gaps:
        if gap.status == "compliant" or not gap.remediation_plan:
            continue
        lines.extend([
            "---",
            "",
            f"## {gap.requirement.article_reference} — {gap.requirement.title}",
            "",
            f"- **Status:** {gap.status}",
            f"- **Priority:** {gap.priority}",
            f"- **Code location:** {gap.code_location or 'n/a'}",
            "",
            f"**Gap:** {gap.gap_description or gap.evidence or 'See scan report.'}",
            "",
            "### Remediation plan",
            "",
            gap.remediation_plan,
            "",
        ])
    return "\n".join(lines)


class FixPrError(Exception):
    """Raised for expected/validation failures so callers can decide how to surface them."""


async def create_fix_pr_for_analysis(db: Session, analysis: Analysis) -> dict:
    """Pushes the approved remediation package to a branch and opens a GitHub PR.

    Shared by the manual "Create Fix PR" API action and the auto-PR autonomy
    path in the orchestrator. Raises FixPrError for validation problems
    (caller decides whether that becomes an HTTP 400 or a logged skip).
    """
    if analysis.status != "complete":
        raise FixPrError("A fix PR can only be created for a completed scan.")
    if analysis.remediation_approval_status != "approved":
        raise FixPrError("Remediation must be approved before a fix PR can be created.")

    project = analysis.project
    if not project or not project.repo_url:
        raise FixPrError("This project has no remote repository URL to open a PR against.")
    if not project.repo_path:
        raise FixPrError("Local clone of the repository not found — run a scan first.")

    token = settings.GITHUB_TOKEN
    if not token:
        raise FixPrError("GITHUB_TOKEN is not configured on the backend.")

    gaps = db.query(ComplianceGap).filter(ComplianceGap.analysis_id == analysis.id).all()
    actionable = [g for g in gaps if g.status != "compliant" and g.remediation_plan]
    if not actionable:
        raise FixPrError("No remediation plans available to commit for this scan.")

    branch = f"compliance-autopilot/scan-{analysis.id}"
    markdown = build_remediation_markdown(analysis, gaps)
    pr_title = f"Compliance remediation package (scan #{analysis.id}, score {analysis.overall_score:.0f}%)"
    pr_body = (
        f"Automated remediation package generated by **Compliance Autopilot** against "
        f"*{analysis.regulation.name}*.\n\n"
        f"- Compliance score: **{analysis.overall_score:.1f}%**\n"
        f"- Gaps with remediation plans: **{len(actionable)}**\n"
        f"- Models: {analysis.model_names}\n"
        f"- Approval: {analysis.remediation_approval_note or 'approved'}\n\n"
        f"See `COMPLIANCE_REMEDIATION.md` in this branch for the full step-by-step plans."
    )

    try:
        await github_service.push_fix_branch(
            repo_path=project.repo_path,
            repo_url=project.repo_url,
            branch=branch,
            file_name="COMPLIANCE_REMEDIATION.md",
            content=markdown,
            commit_message=f"docs: compliance remediation package from scan #{analysis.id}",
            token=token,
        )
        pr_url = await github_service.create_pull_request(
            repo_url=project.repo_url,
            branch=branch,
            title=pr_title,
            body=pr_body,
            token=token,
        )
    except Exception as e:
        logger.exception(f"Fix PR creation failed for analysis {analysis.id}")
        db.add(AuditLog(
            analysis_id=analysis.id,
            agent_name="RemediationEngine",
            action="fix_pr_failed",
            details=str(e)[:500],
            timestamp=datetime.utcnow(),
        ))
        db.commit()
        return {"status": "failed", "branch": branch, "pr_url": None, "message": f"Could not push branch or open PR: {e}"}

    db.add(AuditLog(
        analysis_id=analysis.id,
        agent_name="RemediationEngine",
        action="fix_pr_created",
        details=f"Opened {pr_url} from branch {branch}.",
        timestamp=datetime.utcnow(),
    ))
    db.commit()
    return {"status": "created", "branch": branch, "pr_url": pr_url, "message": "Remediation branch pushed and pull request opened."}
